/* Copyright (c) 2014, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_OTM9605A_QHD_VIDEO_H_
#define _PANEL_OTM9605A_QHD_VIDEO_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/
static struct panel_config otm9605a_qhd_video_panel_data = {
	"qcom,mdss_dsi_otm9605a_qhd_video", "dsi:0:", "qcom,mdss-dsi-panel",
	10, 0, "DISPLAY_1", 0, 0, 60, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution otm9605a_qhd_video_panel_res = {
	800, 1280, 44, 55, 11, 0, 14, 15, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel color information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info otm9605a_qhd_video_color = {
	24, 0, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel on/off command information                                          */
/*---------------------------------------------------------------------------*/

static char otm9605a_qhd_video_on_cmd0[] = {0x02, 0x00, 0x29, 0xC0, 0x50, 0x77, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd1[] = {0x02, 0x00, 0x29, 0xC0, 0xE1, 0x66, 0xff, 0xff}; 
static char otm9605a_qhd_video_on_cmd2[] = {0x02, 0x00, 0x29, 0xC0, 0xDC, 0x67, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd3[] = {0x02, 0x00, 0x29, 0xC0, 0x50, 0x00, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd4[] = {0x02, 0x00, 0x29, 0xC0, 0x58, 0x33, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd5[] = {0x02, 0x00, 0x29, 0xC0, 0x9E, 0x90, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd6[] = {0x02, 0x00, 0x29, 0xC0, 0x9F, 0x24, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd7[] = {0x02, 0x00, 0x29, 0xC0, 0xC5, 0xC2, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd8[] = {0x02, 0x00, 0x29, 0xC0, 0xCF, 0xD8, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd9[] = {0x02, 0x00, 0x29, 0xC0, 0xD2, 0x76, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd10[] = {0x02, 0x00, 0x29, 0xC0, 0x58, 0x00, 0xff, 0xff}; 
static char otm9605a_qhd_video_on_cmd11[] = {0x02, 0x00, 0x29, 0xC0, 0x57, 0x88, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd12[] = {0x02, 0x00, 0x29, 0xC0, 0xBF, 0x02, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd13[] = {0x02, 0x00, 0x29, 0xC0, 0xBE, 0x1A, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd14[] = {0x02, 0x00, 0x29, 0xC0, 0xC1, 0x03, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd15[] = {0x02, 0x00, 0x29, 0xC0, 0xC0, 0x82, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd16[] = {0x02, 0x00, 0x29, 0xC0, 0xDB, 0x02, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd17[] = {0x02, 0x00, 0x29, 0xC0, 0xDA, 0x1A, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd18[] = {0x02, 0x00, 0x29, 0xC0, 0xDD, 0x0B, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd19[] = {0x02, 0x00, 0x29, 0xC0, 0xDC, 0x82, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd20[] = {0x02, 0x00, 0x29, 0xC0, 0xC3, 0x02, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd21[] = {0x02, 0x00, 0x29, 0xC0, 0xDE, 0x08, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd22[] = {0x02, 0x00, 0x29, 0xC0, 0xDF, 0x03, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd23[] = {0x02, 0x00, 0x29, 0xC0, 0xF2, 0x12, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd24[] = {0x02, 0x00, 0x29, 0xC0, 0xF3, 0x14, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd25[] = {0x02, 0x00, 0x29, 0xC0, 0xB7, 0x02, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd26[] = {0x02, 0x00, 0x29, 0xC0, 0x57, 0x00, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd27[] = {0x03, 0x00, 0x29, 0xC0, 0xF0, 0x5a, 0x5a, 0xff};
static char otm9605a_qhd_video_on_cmd28[] = {0x21, 0x00, 0x29, 0xC0, 0xF7, 0x16, 0x16, 0x1A, 0x1A, 0x18, 0x18, 0x19, 0x19, 0x08, 0x08, 0x0A, 0x0A, 0x0C, 0x0C, 0x0E, 0x0E, 0x0F, 0x0F, 0x0D, 0x0D, 0x0B, 0x0B, 0x09, 0x09, 0x19, 0x19, 0x18, 0x18, 0x1A, 0x1A, 0x17, 0x17, 0xff, 0xff, 0xff};        
static char otm9605a_qhd_video_on_cmd29[] = {0x04, 0x00, 0x29, 0xC0, 0xF5, 0x8b, 0x64, 0x72};
static char otm9605a_qhd_video_on_cmd30[] = {0x12, 0x00, 0x29, 0xC0, 0xFA, 0x34, 0x1a, 0x3e, 0x3f, 0x3e, 0x3f, 0x3f, 0x3a, 0x33, 0x3b, 0x3f, 0x3f, 0x38, 0x3f, 0x36, 0x35, 0x19, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd31[] = {0x12, 0x00, 0x29, 0xC0, 0xFB, 0x29, 0x1b, 0x37, 0x37, 0x3c, 0x3d, 0x3f, 0x3f, 0x31, 0x34, 0x34, 0x29, 0x2d, 0x2a, 0x2a, 0x2d, 0x12, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd32[] = {0x02, 0x00, 0x29, 0xC0, 0x53, 0x24, 0xff, 0xff};

static char otm9065a_qhd_video_on_exit_sleep[] = {
	0x11, 0x00, 0x05, 0x80};

static char otm9605a_qhd_video_on_cmd33[] = {0x02, 0x00, 0x29, 0xC0, 0x50, 0x77, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd34[] = {0x02, 0x00, 0x29, 0xC0, 0xE1, 0x66, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd35[] = {0x02, 0x00, 0x29, 0xC0, 0xDC, 0x67, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd36[] = {0x02, 0x00, 0x29, 0xC0, 0xD3, 0xc8, 0xff, 0xff};
static char otm9605a_qhd_video_on_cmd37[] = {0x02, 0x00, 0x29, 0xC0, 0x50, 0x00, 0xff, 0xff};  
static char otm9605a_qhd_video_on_cmd38[] = {0x03, 0x00, 0x29, 0xC0, 0xf0, 0x5a, 0x5a, 0xff}; 
static char otm9605a_qhd_video_on_cmd39[] = {0x02, 0x00, 0x29, 0xC0, 0xf5, 0xb0, 0xff, 0xff};

static char otm9065a_qhd_video_on_display_on[] = {
	0x29, 0x00, 0x05, 0x80};

static struct mipi_dsi_cmd otm9605a_qhd_video_on_command[] = {
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd0), otm9605a_qhd_video_on_cmd0, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd1), otm9605a_qhd_video_on_cmd1, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd2), otm9605a_qhd_video_on_cmd2, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd3), otm9605a_qhd_video_on_cmd3, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd4), otm9605a_qhd_video_on_cmd4, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd5), otm9605a_qhd_video_on_cmd5, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd6), otm9605a_qhd_video_on_cmd6, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd7), otm9605a_qhd_video_on_cmd7, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd8), otm9605a_qhd_video_on_cmd8, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd9), otm9605a_qhd_video_on_cmd9, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd10), otm9605a_qhd_video_on_cmd10, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd11), otm9605a_qhd_video_on_cmd11, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd12), otm9605a_qhd_video_on_cmd12, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd13), otm9605a_qhd_video_on_cmd13, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd14), otm9605a_qhd_video_on_cmd14, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd15), otm9605a_qhd_video_on_cmd15, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd16), otm9605a_qhd_video_on_cmd16, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd17), otm9605a_qhd_video_on_cmd17, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd18), otm9605a_qhd_video_on_cmd18, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd19), otm9605a_qhd_video_on_cmd19, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd20), otm9605a_qhd_video_on_cmd20, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd21), otm9605a_qhd_video_on_cmd21, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd22), otm9605a_qhd_video_on_cmd22, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd23), otm9605a_qhd_video_on_cmd23, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd24), otm9605a_qhd_video_on_cmd24, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd25), otm9605a_qhd_video_on_cmd25, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd26), otm9605a_qhd_video_on_cmd26, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd27), otm9605a_qhd_video_on_cmd27, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd28), otm9605a_qhd_video_on_cmd28, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd29), otm9605a_qhd_video_on_cmd29, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd30), otm9605a_qhd_video_on_cmd30, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd31), otm9605a_qhd_video_on_cmd31, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd32), otm9605a_qhd_video_on_cmd32, 0x00},

{ARRAY_SIZE(otm9065a_qhd_video_on_exit_sleep), otm9065a_qhd_video_on_exit_sleep, 0x78},

{ARRAY_SIZE(otm9605a_qhd_video_on_cmd33), otm9605a_qhd_video_on_cmd33, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd34), otm9605a_qhd_video_on_cmd34, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd35), otm9605a_qhd_video_on_cmd35, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd36), otm9605a_qhd_video_on_cmd36, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd37), otm9605a_qhd_video_on_cmd37, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd38), otm9605a_qhd_video_on_cmd38, 0x00},
{ARRAY_SIZE(otm9605a_qhd_video_on_cmd39), otm9605a_qhd_video_on_cmd39, 0x00},

{ARRAY_SIZE(otm9065a_qhd_video_on_display_on), otm9065a_qhd_video_on_display_on, 0x14},	
};

//#define OTM9605A_QHD_SDTM800_VIDEO_ON_COMMAND  40


static char otm9605a_qhd_videooff_cmd0[] = {
	0x28, 0x00, 0x05, 0x80
};

static char otm9605a_qhd_videooff_cmd1[] = {
	0x10, 0x00, 0x05, 0x80
};

static struct mipi_dsi_cmd otm9605a_qhd_video_off_command[] = {
	{0x4, otm9605a_qhd_videooff_cmd0, 0x32},
	{0x4, otm9605a_qhd_videooff_cmd1, 0x78}
};

#define OTM9605A_QHD_VIDEO_OFF_COMMAND 2


static struct command_state otm9605a_qhd_video_state = {
	0, 1
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/
static struct commandpanel_info otm9605a_qhd_video_command_panel = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/
static struct videopanel_info otm9605a_qhd_video_video_panel = {
	1, 0, 0, 0, 1, 1, 2, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane configuration                                                        */
/*---------------------------------------------------------------------------*/
static struct lane_configuration otm9605a_qhd_video_lane_config = {
	4, 0, 1, 1, 1, 1
};

/*---------------------------------------------------------------------------*/
/* Panel timing                                                              */
/*---------------------------------------------------------------------------*/
static const uint32_t otm9605a_qhd_video_timings[] = {
	0x93, 0x1F, 0x17, 0x00, 0x2F, 0x2E, 0x1C, 0x21, 0x26, 0x03, 0x04, 0x00
};

static struct panel_timing otm9605a_qhd_video_timing_info = {
	0, 4, 0x20, 0x2D
};

/*---------------------------------------------------------------------------*/
/* Panel reset sequence                                                      */
/*---------------------------------------------------------------------------*/
static struct panel_reset_sequence otm9605a_qhd_video_reset_seq = {
	{1, 0, 1, }, {10, 50, 50, }, 2
};

/*---------------------------------------------------------------------------*/
/* Backlight setting                                                         */
/*---------------------------------------------------------------------------*/
static struct backlight otm9605a_qhd_video_backlight = {
	0, 1, 255, 0, 0, 0
};

#endif /*_PANEL_OTM9605A_QHD_VIDEO_H_*/
