/* Copyright (c) 2013, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_OTM8019_TM_VIDEO_H_

#define _PANEL_OTM8019_TM_VIDEO_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/

static struct panel_config otm8019_tm_video_panel_data = {
  "qcom,mdss_dsi_otm8019_tm_video", "dsi:0:", "qcom,mdss-dsi-panel",
	10, 0, "DISPLAY_1", 0, 0, 60, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution otm8019_tm_video_panel_res = {
  480, 800, 40, 40, 10, 0, 16, 14, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel Color Information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info otm8019_tm_video_color = {
  24, 0, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel Command information                                                 */
/*---------------------------------------------------------------------------*/

/********************************************************************************
*       ic=otm8019; glass=tm; module=tm; size=3.97; wvga; 480x800         *
*********************************************************************************/
static char otm8019_tm_cmd1[] = {0X02,0X00,0X29,0XC0,0x00,0x00,0xff,0xff};
static char otm8019_tm_cmd2[] = {0X04,0X00,0X29,0XC0,0xff,0x80,0x19,0x01};
static char otm8019_tm_cmd3[] = {0X02,0X00,0X29,0XC0,0x00,0x80,0xff,0xff};
static char otm8019_tm_cmd4[] = {0X03,0X00,0X29,0XC0,0xff,0x80,0x19,0xff};
static char otm8019_tm_cmd5[] = {0X02,0X00,0X29,0XC0,0x00,0xb4,0xff,0xff};
static char otm8019_tm_cmd6[] = {0X02,0X00,0X29,0XC0,0xc0,0x70,0xff,0xff};
static char otm8019_tm_cmd7[] = {0X02,0X00,0X29,0XC0,0x00,0x89,0xff,0xff};
static char otm8019_tm_cmd8[] = {0X02,0X00,0X29,0XC0,0xc4,0x08,0xff,0xff};
static char otm8019_tm_cmd9[] = {0X02,0X00,0X29,0XC0,0x00,0xa3,0xff,0xff};
static char otm8019_tm_cmd10[] = {0X02,0X00,0X29,0XC0,0xc0,0x1b,0xff,0xff};
static char otm8019_tm_cmd11[] = {0X02,0X00,0X29,0XC0,0x00,0x82,0xff,0xff};
static char otm8019_tm_cmd12[] = {0X02,0X00,0X29,0XC0,0xc5,0xb0,0xff,0xff};
static char otm8019_tm_cmd13[] = {0X02,0X00,0X29,0XC0,0x00,0x90,0xff,0xff};
static char otm8019_tm_cmd14[] = {0X03,0X00,0X29,0XC0,0xc5,0x8e,0xb7,0xff};
static char otm8019_tm_cmd15[] = {0X02,0X00,0X29,0XC0,0x00,0x00,0xff,0xff};
static char otm8019_tm_cmd16[] = {0X03,0X00,0X29,0XC0,0xd8,0x73,0x73,0xff};
static char otm8019_tm_cmd17[] = {0X02,0X00,0X29,0XC0,0x00,0x00,0xff,0xff};
static char otm8019_tm_cmd18[] = {0X02,0X00,0X29,0XC0,0xd9,0x78,0xff,0xff};
static char otm8019_tm_cmd19[] = {0X02,0X00,0X29,0XC0,0x00,0xa1,0xff,0xff};
static char otm8019_tm_cmd20[] = {0X02,0X00,0X29,0XC0,0xc1,0x08,0xff,0xff};
static char otm8019_tm_cmd21[] = {0X02,0X00,0X29,0XC0,0x00,0x81,0xff,0xff};
static char otm8019_tm_cmd22[] = {0X02,0X00,0X29,0XC0,0xc4,0x83,0xff,0xff};
static char otm8019_tm_cmd23[] = {0X02,0X00,0X29,0XC0,0x00,0x92,0xff,0xff};
static char otm8019_tm_cmd24[] = {0X02,0X00,0X29,0XC0,0xc5,0x01,0xff,0xff};
static char otm8019_tm_cmd25[] = {0X02,0X00,0X29,0XC0,0x00,0xb1,0xff,0xff};
static char otm8019_tm_cmd26[] = {0X02,0X00,0X29,0XC0,0xc5,0xa9,0xff,0xff};
static char otm8019_tm_cmd27[] = {0X02,0X00,0X29,0XC0,0x00,0x90,0xff,0xff};
static char otm8019_tm_cmd28[] = {0X07,0X00,0X29,0XC0,0xc0,0x00,0x15,0x00,0x00,0x00,0x03,0xff};
static char otm8019_tm_cmd29[] = {0X02,0X00,0X29,0XC0,0x00,0xa6,0xff,0xff};
static char otm8019_tm_cmd30[] = {0X04,0X00,0X29,0XC0,0xc1,0x00,0x00,0x00};
static char otm8019_tm_cmd31[] = {0X02,0X00,0X29,0XC0,0x00,0x80,0xff,0xff};
static char otm8019_tm_cmd32[] = {0X07,0X00,0X29,0XC0,0xce,0x83,0x01,0x11,0x82,0x01,0x11,0xff};
static char otm8019_tm_cmd33[] = {0X02,0X00,0X29,0XC0,0x00,0xa0,0xff,0xff};
static char otm8019_tm_cmd34[] = {0X0F,0X00,0X29,0XC0,0xce,0x18,0x01,0x03,0x1d,0x00,0x11,0x00,0x18,0x00,0x03,0x1e,0x00,0x11,0x00,0xff};
static char otm8019_tm_cmd35[] = {0X02,0X00,0X29,0XC0,0x00,0xb0,0xff,0xff};
static char otm8019_tm_cmd36[] = {0X0F,0X00,0X29,0XC0,0xce,0x10,0x00,0x03,0x1f,0x00,0x11,0x00,0x10,0x01,0x03,0x20,0x00,0x11,0x00,0xff};
static char otm8019_tm_cmd37[] = {0X02,0X00,0X29,0XC0,0x00,0xc6,0xff,0xff};
static char otm8019_tm_cmd38[] = {0X02,0X00,0X29,0XC0,0xcf,0x01,0xff,0xff};
static char otm8019_tm_cmd39[] = {0X02,0X00,0X29,0XC0,0x00,0xc0,0xff,0xff};
static char otm8019_tm_cmd40[] = {0X03,0X00,0X29,0XC0,0xcb,0x01,0x01,0xff};
static char otm8019_tm_cmd41[] = {0X02,0X00,0X29,0XC0,0x00,0xc6,0xff,0xff};
static char otm8019_tm_cmd42[] = {0X04,0X00,0X29,0XC0,0xcb,0x01,0x01,0x01};
static char otm8019_tm_cmd43[] = {0X02,0X00,0X29,0XC0,0x00,0xdc,0xff,0xff};
static char otm8019_tm_cmd44[] = {0X04,0X00,0X29,0XC0,0xcb,0x01,0x01,0x01};
static char otm8019_tm_cmd45[] = {0X02,0X00,0X29,0XC0,0x00,0xe4,0xff,0xff};
static char otm8019_tm_cmd46[] = {0X03,0X00,0X29,0XC0,0xcb,0x01,0x11,0xff};
static char otm8019_tm_cmd47[] = {0X02,0X00,0X29,0XC0,0x00,0x80,0xff,0xff};
static char otm8019_tm_cmd48[] = {0X03,0X00,0X29,0XC0,0xcc,0x26,0x25,0xff};
static char otm8019_tm_cmd49[] = {0X02,0X00,0X29,0XC0,0x00,0x86,0xff,0xff};
static char otm8019_tm_cmd50[] = {0X04,0X00,0X29,0XC0,0xcc,0x0c,0x0a,0x02};
static char otm8019_tm_cmd51[] = {0X02,0X00,0X29,0XC0,0x00,0xa2,0xff,0xff};
static char otm8019_tm_cmd52[] = {0X04,0X00,0X29,0XC0,0xcc,0x01,0x09,0x0b};
static char otm8019_tm_cmd53[] = {0X02,0X00,0X29,0XC0,0x00,0xa9,0xff,0xff};
static char otm8019_tm_cmd54[] = {0X03,0X00,0X29,0XC0,0xcc,0x25,0x26,0xff};
static char otm8019_tm_cmd55[] = {0X02,0X00,0X29,0XC0,0x00,0xb0,0xff,0xff};
static char otm8019_tm_cmd56[] = {0X03,0X00,0X29,0XC0,0xcc,0x25,0x26,0xff};
static char otm8019_tm_cmd57[] = {0X02,0X00,0X29,0XC0,0x00,0xb6,0xff,0xff};
static char otm8019_tm_cmd58[] = {0X04,0X00,0X29,0XC0,0xcc,0x09,0x0b,0x01};
static char otm8019_tm_cmd59[] = {0X02,0X00,0X29,0XC0,0x00,0xd2,0xff,0xff};
static char otm8019_tm_cmd60[] = {0X04,0X00,0X29,0XC0,0xcc,0x02,0x0c,0x0a};
static char otm8019_tm_cmd61[] = {0X02,0X00,0X29,0XC0,0x00,0xd9,0xff,0xff};
static char otm8019_tm_cmd62[] = {0X03,0X00,0X29,0XC0,0xcc,0x26,0x25,0xff};
static char otm8019_tm_cmd63[] = {0X02,0X00,0X29,0XC0,0x00,0x80,0xff,0xff};
static char otm8019_tm_cmd64[] = {0X02,0X00,0X29,0XC0,0xc4,0x30,0xff,0xff};
static char otm8019_tm_cmd65[] = {0X02,0X00,0X29,0XC0,0x00,0x98,0xff,0xff};
static char otm8019_tm_cmd66[] = {0X02,0X00,0X29,0XC0,0xc0,0x00,0xff,0xff};
static char otm8019_tm_cmd67[] = {0X02,0X00,0X29,0XC0,0x00,0xa9,0xff,0xff};
static char otm8019_tm_cmd68[] = {0X02,0X00,0X29,0XC0,0xc0,0x06,0xff,0xff};
static char otm8019_tm_cmd69[] = {0X02,0X00,0X29,0XC0,0x00,0xb0,0xff,0xff};
static char otm8019_tm_cmd70[] = {0X04,0X00,0X29,0XC0,0xc1,0x20,0x00,0x00};
static char otm8019_tm_cmd71[] = {0X02,0X00,0X29,0XC0,0x00,0xe1,0xff,0xff};
static char otm8019_tm_cmd72[] = {0X03,0X00,0X29,0XC0,0xc0,0x40,0x18,0xff};
static char otm8019_tm_cmd73[] = {0X02,0X00,0X29,0XC0,0x00,0x80,0xff,0xff};
static char otm8019_tm_cmd74[] = {0X03,0X00,0X29,0XC0,0xc1,0x03,0x33,0xff};
static char otm8019_tm_cmd75[] = {0X02,0X00,0X29,0XC0,0x00,0xa0,0xff,0xff};
static char otm8019_tm_cmd76[] = {0X02,0X00,0X29,0XC0,0xc1,0xe8,0xff,0xff};
static char otm8019_tm_cmd77[] = {0X02,0X00,0X29,0XC0,0x00,0x90,0xff,0xff};
static char otm8019_tm_cmd78[] = {0X02,0X00,0X29,0XC0,0xb6,0xb4,0xff,0xff};
static char otm8019_tm_cmd79[] = {0X02,0X00,0X29,0XC0,0x00,0x00,0xff,0xff};
static char otm8019_tm_cmd80[] = {0X15,0X00,0X29,0XC0,0xe1,0x05,0x36,0x48,0x57,0x69,0x78,0x7b,0xa6,0x96,0xaf,0x55,0x41,0x52,0x30,0x2e,0x21,0x18,0x0f,0x07,0x03,0xff,0xff,0xff};
static char otm8019_tm_cmd81[] = {0X02,0X00,0X29,0XC0,0x00,0x00,0xff,0xff};
static char otm8019_tm_cmd82[] = {0X15,0X00,0X29,0XC0,0xe2,0x05,0x36,0x48,0x57,0x69,0x78,0x7b,0xa6,0x96,0xaf,0x55,0x41,0x52,0x30,0x2e,0x21,0x18,0x0f,0x07,0x03,0xff,0xff,0xff};
static char otm8019_tm_cmd83[] = {0X02,0X00,0X29,0XC0,0x00,0x80,0xff,0xff};
static char otm8019_tm_cmd84[] = {0X02,0X00,0X29,0XC0,0xc4,0x30,0xff,0xff};
static char otm8019_tm_cmd85[] = {0X02,0X00,0X29,0XC0,0x00,0x98,0xff,0xff};
static char otm8019_tm_cmd86[] = {0X02,0X00,0X29,0XC0,0xc0,0x00,0xff,0xff};
static char otm8019_tm_cmd87[] = {0X02,0X00,0X29,0XC0,0x00,0xa9,0xff,0xff};
static char otm8019_tm_cmd88[] = {0X02,0X00,0X29,0XC0,0xc0,0x0a,0xff,0xff};
static char otm8019_tm_cmd89[] = {0X02,0X00,0X29,0XC0,0x00,0xb0,0xff,0xff};
static char otm8019_tm_cmd90[] = {0X04,0X00,0X29,0XC0,0xc1,0x20,0x00,0x00};
static char otm8019_tm_cmd91[] = {0X02,0X00,0X29,0XC0,0x00,0xe1,0xff,0xff};
static char otm8019_tm_cmd92[] = {0X03,0X00,0X29,0XC0,0xc0,0x40,0x30,0xff};
static char otm8019_tm_cmd93[] = {0X02,0X00,0X29,0XC0,0x00,0x80,0xff,0xff};
static char otm8019_tm_cmd94[] = {0X03,0X00,0X29,0XC0,0xc1,0x03,0x33,0xff};
static char otm8019_tm_cmd95[] = {0X02,0X00,0X29,0XC0,0x00,0xa0,0xff,0xff};
static char otm8019_tm_cmd96[] = {0X02,0X00,0X29,0XC0,0xc1,0xe8,0xff,0xff};
static char otm8019_tm_cmd97[] = {0X02,0X00,0X29,0XC0,0x00,0x90,0xff,0xff};
static char otm8019_tm_cmd98[] = {0X02,0X00,0X29,0XC0,0xb6,0xb4,0xff,0xff};
static char otm8019_tm_cmd99[] = {0X02,0X00,0X29,0XC0,0x00,0x00,0xff,0xff};
static char otm8019_tm_cmd100[] = {0X02,0X00,0X29,0XC0,0x0a,0x0a,0xff,0xff};
static char otm8019_tm_cmd101[] = {0X02,0X00,0X29,0XC0,0x00,0x00,0xff,0xff};
static char otm8019_tm_cmd102[] = {0X02,0X00,0X29,0XC0,0xfb,0x01,0xff,0xff};
static char otm8019_tm_cmd103[] = {0X02,0X00,0X29,0XC0,0x00,0x00,0xff,0xff};
static char otm8019_tm_cmd104[] = {0X04,0X00,0X29,0XC0,0xff,0xff,0xff,0xff};

static char otm8019_tm_video_on_exit_sleep[] = {
	0x11,0x00,0x05,0x80};

static char otm8019_tm_video_on_display_on[] = {
	0x29,0x00,0x05,0x80};

static struct mipi_dsi_cmd otm8019_tm_video_on_command[] = {
	{ARRAY_SIZE(otm8019_tm_cmd1), otm8019_tm_cmd1, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd2), otm8019_tm_cmd2, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd3), otm8019_tm_cmd3, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd4), otm8019_tm_cmd4, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd5), otm8019_tm_cmd5, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd6), otm8019_tm_cmd6, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd7), otm8019_tm_cmd7, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd8), otm8019_tm_cmd8, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd9), otm8019_tm_cmd9, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd10), otm8019_tm_cmd10, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd11), otm8019_tm_cmd11, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd12), otm8019_tm_cmd12, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd13), otm8019_tm_cmd13, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd14), otm8019_tm_cmd14, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd15), otm8019_tm_cmd15, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd16), otm8019_tm_cmd16, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd17), otm8019_tm_cmd17, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd18), otm8019_tm_cmd18, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd19), otm8019_tm_cmd19, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd20), otm8019_tm_cmd20, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd21), otm8019_tm_cmd21, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd22), otm8019_tm_cmd22, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd23), otm8019_tm_cmd23, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd24), otm8019_tm_cmd24, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd25), otm8019_tm_cmd25, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd26), otm8019_tm_cmd26, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd27), otm8019_tm_cmd27, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd28), otm8019_tm_cmd28, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd29), otm8019_tm_cmd29, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd30), otm8019_tm_cmd30, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd31), otm8019_tm_cmd31, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd32), otm8019_tm_cmd32, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd33), otm8019_tm_cmd33, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd34), otm8019_tm_cmd34, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd35), otm8019_tm_cmd35, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd36), otm8019_tm_cmd36, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd37), otm8019_tm_cmd37, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd38), otm8019_tm_cmd38, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd39), otm8019_tm_cmd39, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd40), otm8019_tm_cmd40, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd41), otm8019_tm_cmd41, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd42), otm8019_tm_cmd42, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd43), otm8019_tm_cmd43, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd44), otm8019_tm_cmd44, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd45), otm8019_tm_cmd45, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd46), otm8019_tm_cmd46, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd47), otm8019_tm_cmd47, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd48), otm8019_tm_cmd48, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd49), otm8019_tm_cmd49, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd50), otm8019_tm_cmd50, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd51), otm8019_tm_cmd51, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd52), otm8019_tm_cmd52, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd53), otm8019_tm_cmd53, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd54), otm8019_tm_cmd54, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd55), otm8019_tm_cmd55, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd56), otm8019_tm_cmd56, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd57), otm8019_tm_cmd57, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd58), otm8019_tm_cmd58, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd59), otm8019_tm_cmd59, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd60), otm8019_tm_cmd60, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd61), otm8019_tm_cmd61, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd62), otm8019_tm_cmd62, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd63), otm8019_tm_cmd63, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd64), otm8019_tm_cmd64, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd65), otm8019_tm_cmd65, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd66), otm8019_tm_cmd66, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd67), otm8019_tm_cmd67, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd68), otm8019_tm_cmd68, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd69), otm8019_tm_cmd69, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd70), otm8019_tm_cmd70, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd71), otm8019_tm_cmd71, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd72), otm8019_tm_cmd72, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd73), otm8019_tm_cmd73, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd74), otm8019_tm_cmd74, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd75), otm8019_tm_cmd75, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd76), otm8019_tm_cmd76, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd77), otm8019_tm_cmd77, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd78), otm8019_tm_cmd78, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd79), otm8019_tm_cmd79, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd80), otm8019_tm_cmd80, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd81), otm8019_tm_cmd81, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd82), otm8019_tm_cmd82, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd83), otm8019_tm_cmd83, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd84), otm8019_tm_cmd84, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd85), otm8019_tm_cmd85, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd86), otm8019_tm_cmd86, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd87), otm8019_tm_cmd87, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd88), otm8019_tm_cmd88, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd89), otm8019_tm_cmd89, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd90), otm8019_tm_cmd90, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd91), otm8019_tm_cmd91, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd92), otm8019_tm_cmd92, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd93), otm8019_tm_cmd93, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd94), otm8019_tm_cmd94, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd95), otm8019_tm_cmd95, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd96), otm8019_tm_cmd96, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd97), otm8019_tm_cmd97, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd98), otm8019_tm_cmd98, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd99), otm8019_tm_cmd99, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd100), otm8019_tm_cmd100, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd101), otm8019_tm_cmd101, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd102), otm8019_tm_cmd102, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd103), otm8019_tm_cmd103, 0x00},
	{ARRAY_SIZE(otm8019_tm_cmd104), otm8019_tm_cmd104, 0x00},

	{ARRAY_SIZE(otm8019_tm_video_on_exit_sleep), otm8019_tm_video_on_exit_sleep, 0x78},
	{ARRAY_SIZE(otm8019_tm_video_on_display_on), otm8019_tm_video_on_display_on, 0x32},

};

static char otm8019_tm_videooff_cmd0[] = {
0x28, 0x00, 0x05, 0x80 };


static char otm8019_tm_videooff_cmd1[] = {
0x10, 0x00, 0x05, 0x80 };




static struct mipi_dsi_cmd otm8019_tm_video_off_command[] = {
{ 0x4 , otm8019_tm_videooff_cmd0},
{ 0x4 , otm8019_tm_videooff_cmd1}
};
#define OTM8019_TM_VIDEO_OFF_COMMAND 2


static struct command_state otm8019_tm_video_state = {
	0, 0
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/

static struct commandpanel_info otm8019_tm_video_command_panel = {
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/

static struct videopanel_info otm8019_tm_video_video_panel = {
	1, 0, 0, 0, 1, 1, 2, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane Configuration                                                        */
/*---------------------------------------------------------------------------*/

static struct lane_configuration otm8019_tm_video_lane_config = {
  2, 0, 1, 1, 0, 0
};


/*---------------------------------------------------------------------------*/
/* Panel Timing                                                              */
/*---------------------------------------------------------------------------*/
static const uint32_t otm8019_tm_video_timings[] = {
	//0x6B, 0x14, 0x0C, 0x00, 0x36, 0x3A, 0x12, 0x18, 0x11, 0x03, 0x04, 0x00
	//0x8B, 0x1f, 0x14, 0x00, 0x45, 0x4A, 0x19, 0x23, 0x23, 0x03, 0x04, 0x00
	0x2B, 0x14, 0x0c, 0x00, 0x36, 0x38, 0x12, 0x18, 0x11, 0x03, 0x04, 0x00
};

static struct panel_timing otm8019_tm_video_timing_info = {
	0, 4, 0x04, 0x1d
};

/*---------------------------------------------------------------------------*/
/* Panel Reset Sequence                                                      */
/*---------------------------------------------------------------------------*/
static struct panel_reset_sequence otm8019_tm_video_reset_seq = {
  { 1, 0, 1, }, { 10, 20, 120, }, 2
};

/*---------------------------------------------------------------------------*/
/* Backlight Settings                                                        */
/*---------------------------------------------------------------------------*/

static struct backlight otm8019_tm_video_backlight = {
  0, 1, 255, 0, 1, 0
};


#endif /*_PANEL_OTM8019_TM_VIDEO_H_*/

