/* Copyright (c) 2015, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_R61318_HD_VIDEO_H_
#define _PANEL_R61318_HD_VIDEO_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/
static struct panel_config r61318_hd_video_panel_data = {
	"qcom,mdss_dsi_r61318_hd_video", "dsi:0:", "qcom,mdss-dsi-panel",
	10, 0, "DISPLAY_1", 0, 0, 60, 0, 0, 0, 1, 50000, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution r61318_hd_video_panel_res = {
	//720, 1280, 100, 100, 20, 0, 17, 10, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0
	720, 1280,100, 60, 2, 0, 8, 8, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel color information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info r61318_hd_video_color = {
	24, 0, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel on/off command information                                          */
/*---------------------------------------------------------------------------*/
#if 0
static char r61318_hd_video_on_cmd0[] = {
	0x02, 0x00, 0x39, 0xC0,
	0xB0,0x00,0xff,0xff
};

static char r61318_hd_video_on_cmd1[] = {
	0x02, 0x00, 0x39, 0xC0,
	0xE3,0x01,0xff,0xff
};

static char r61318_hd_video_on_cmd2[] = {
	0x07, 0x00, 0x39, 0xC0,
	0xC0,0x23,0xB2,0x0D,
	0x10,0x02,0x80,0xff
};

static char r61318_hd_video_on_cmd3[] = {
	0x08, 0x00, 0x39, 0xC0,
	0xC1,0xA8,0xA8,0x00,
	0x00,0x04,0x04,0x11
};

static char r61318_hd_video_on_cmd4[] = {
	0x02, 0x00, 0x39, 0xC0,
	0xC3,0x20,0xff,0xff
};

static char r61318_hd_video_on_cmd5[] = {
	0x04, 0x00, 0x39, 0xC0,
	0xC4,0xB4,0xD9,0x00
};

static char r61318_hd_video_on_cmd6[] = {
	0x04, 0x00, 0x39, 0xC0,
	0xC5,0x0A,0x05,0x13
};

static char r61318_hd_video_on_cmd7[] = {
	0x02, 0x00, 0x39, 0xC0,
	0xC6,0x21,0xff,0xff
};

static char r61318_hd_video_on_cmd8[] = {
	0x02, 0x00, 0x39, 0xC0,
	0xCD,0x00,0xff,0xff

};

static char r61318_hd_video_on_cmd9[] = {
	0x1d, 0x00, 0x39, 0xC0,
	0xC8,0xE0,0xBD,0xF7,
	0x20,0x78,0x4F,0x7C,
	0x59,0xBE,0xB9,0x07,
	0xA3,0xF7,0xDE,0x7B,
	0xEF,0x7D,0x84,0xCF,
	0x35,0xBF,0x8A,0x27,
	0xDE,0x07,0xE0,0xBD,
	0xF7,0xff,0xff,0xff
};

static char r61318_hd_video_on_cmd10[] = {
	0x04, 0x00, 0x39, 0xC0,
	0xD0,0x06,0x55,0x50
};

static char r61318_hd_video_on_cmd11[] = {
	0x02, 0x00, 0x39, 0xC0,
	0xD1,0x03,0xff,0xff
};

static char r61318_hd_video_on_cmd12[] = {
	0x03, 0x00, 0x39, 0xC0,
	0xD2,0x81,0x1F,0xff
};

static char r61318_hd_video_on_cmd13[] = {
	0x03, 0x00, 0x39, 0xC0,
	0xD5,0x28,0x28,0xff
};

static char r61318_hd_video_on_cmd14[] = {
	0x02, 0x00, 0x39, 0xC0,
	0xE5,0x03,0xff,0xff
};

static char r61318_hd_video_on_cmd15[] = {
	0x02, 0x00, 0x39, 0xC0,
	0xD4,0x76,0xff,0xff
};
static char r61318_hd_video_on_cmd16[] = {
	0x1f, 0x00, 0x39, 0xC0,
	0x00,0x05,0x0A,0x10,
	0x17,0x1C,0x1F,0x1C,
	0x26,0x24,0x20,0x13,
	0x13,0x0F,0x00,0x00,
	0x05,0x0A,0x10,0x17,
	0x1C,0x1F,0x1C,0x26,
	0x24,0x20,0x13,0x13,
	0x0F,0x00,0x00,0xff
};
#else
static char r61318_hd_video_on_cmd0[] = {
	0x02, 0x00, 0x29, 0xC0,
	0xb0, 0x00,0xff,0xff
};

static char r61318_hd_video_on_cmd1[] = {
	0x02, 0x00, 0x29, 0xC0,
	0xe3, 0x01,0xff,0xff
};

static char r61318_hd_video_on_cmd2[] = {
	0x04, 0x00, 0x29, 0xC0,
	0xC4,0xB4,0xD9,0x00
};

static char r61318_hd_video_on_cmd3[] = {
	0x07, 0x00, 0x29, 0xC0,
	0xC0,0x23,0xB2,0x0D,
	0x10,0x02,0x80,0xff
};

static char r61318_hd_video_on_cmd4[] = {
	0x08, 0x00, 0x29, 0xC0,
	0xC1,0xA8,0xA8,0x33,
	0x33,0x10,0x10,0x33
};

static char r61318_hd_video_on_cmd5[] = {
	0x04, 0x00, 0x29, 0xC0,
	0xC5,0x0A,0x05,0x13
};

static char r61318_hd_video_on_cmd6[] = {
	0x02, 0x00, 0x29, 0xC0,
	0xC6,0x21,0xff,0xff
};

static char r61318_hd_video_on_cmd7[] = {
	0x1d, 0x00, 0x29, 0xC0,
	0xC8,0xE0,0xBD,0xF7,
	0x20,0x78,0x4F,0x7C,
	0x59,0xBE,0xB9,0x07,
	0xA3,0xF7,0xDE,0x7B,
	0xEF,0x7D,0x84,0xCF,
	0x35,0xBF,0x8A,0x27,
	0xDE,0x07,0xE0,0xBD,
	0xF7,0xff,0xff,0xff
};

static char r61318_hd_video_on_cmd8[] = {
	0x1d, 0x00, 0x29, 0xC0,
	0xCA,0x0a,0x04,0x07,
	0x0B,0x12,0x17,0x1A,
	0x19,0x28,0x27,0x22,
	0x1A,0x13,0x0F,0x09,
	0x00,0x04,0x07,0x0B,
	0x12,0x17,0x1A,0x19,
	0x28,0x27,0x22,0x1A,
	0x13,0xff,0xff,0xff

};
/*
static char r61318_hd_video_on_cmd8[] = {
	0x1D, 0x00, 0x29, 0xC0,
	0xca,0x0a,0x04,0x07,
	0x0b,0x12,0x17,0x1a,
	0x19,0x28,0x27,0x22,
	0x1a,0x13,0x0f,0x09,
	0x00,0x04,0x07,0x0b,
	0x12,0x17,0x1a,0x19,
	0x28,0x27,0x22,0x1a,
	0x13,0xff,0xff,0xff
};
*/
static char r61318_hd_video_on_cmd9[] = {
	0x02, 0x00, 0x29, 0xC0,
	0xCD,0x00,0xff,0xff
};

static char r61318_hd_video_on_cmd10[] = {
	0x04, 0x00, 0x29, 0xC0,
	0xD0,0x06,0x10,0x50
};

static char r61318_hd_video_on_cmd11[] = {
	0x02, 0x00, 0x29, 0xC0,
	0xD1,0x03,0xff,0xff
};

static char r61318_hd_video_on_cmd12[] = {
	0x03, 0x00, 0x29, 0xC0,
	0xD2,0x81,0x1F,0xff
};

static char r61318_hd_video_on_cmd13[] = {
	0x02, 0x00, 0x29, 0xC0,
	0xE5,0x03,0xff,0xff
};

static char r61318_hd_video_on_cmd14[] = {
	0x02, 0x00, 0x29, 0xC0,
	0xD4,0x85,0xff,0xff
};

static char r61318_hd_video_on_cmd15[] = {
	0x03, 0x00, 0x29, 0xC0,
	0xD5,0x34,0x34,0xff
};
#endif

static char r61318_hd_video_on_cmd19[] = {
	0x11, 0x00, 0x05, 0x80
};

static char r61318_hd_video_on_cmd20[] = {
	0x29, 0x00, 0x05, 0x80
};


static struct mipi_dsi_cmd r61318_hd_video_on_command[] = {
	{ARRAY_SIZE(r61318_hd_video_on_cmd0), r61318_hd_video_on_cmd0, 0x00},
	{ARRAY_SIZE(r61318_hd_video_on_cmd1), r61318_hd_video_on_cmd1, 0x00},
	{ARRAY_SIZE(r61318_hd_video_on_cmd2), r61318_hd_video_on_cmd2, 0x00},
	{ARRAY_SIZE(r61318_hd_video_on_cmd3), r61318_hd_video_on_cmd3, 0x00},
	{ARRAY_SIZE(r61318_hd_video_on_cmd4), r61318_hd_video_on_cmd4, 0x00},
	{ARRAY_SIZE(r61318_hd_video_on_cmd5), r61318_hd_video_on_cmd5, 0x00},
	{ARRAY_SIZE(r61318_hd_video_on_cmd6), r61318_hd_video_on_cmd6, 0x00},
	{ARRAY_SIZE(r61318_hd_video_on_cmd7), r61318_hd_video_on_cmd7, 0x00},
	{ARRAY_SIZE(r61318_hd_video_on_cmd8), r61318_hd_video_on_cmd8, 0x00},
	{ARRAY_SIZE(r61318_hd_video_on_cmd9), r61318_hd_video_on_cmd9, 0x00},
	{ARRAY_SIZE(r61318_hd_video_on_cmd10), r61318_hd_video_on_cmd10, 0x00},
	{ARRAY_SIZE(r61318_hd_video_on_cmd11), r61318_hd_video_on_cmd11, 0x00},
	{ARRAY_SIZE(r61318_hd_video_on_cmd12), r61318_hd_video_on_cmd12, 0x00},
	{ARRAY_SIZE(r61318_hd_video_on_cmd13), r61318_hd_video_on_cmd13, 0x00},
	{ARRAY_SIZE(r61318_hd_video_on_cmd14), r61318_hd_video_on_cmd14, 0x00},
	{ARRAY_SIZE(r61318_hd_video_on_cmd15), r61318_hd_video_on_cmd15, 0x00},
	//{ARRAY_SIZE(r61318_hd_video_on_cmd16), r61318_hd_video_on_cmd16, 0x00},

	{ARRAY_SIZE(r61318_hd_video_on_cmd19), r61318_hd_video_on_cmd19, 0x96},
	{ARRAY_SIZE(r61318_hd_video_on_cmd20), r61318_hd_video_on_cmd20, 0x32},

};

#define R61318_HD_VIDEO_ON_COMMAND 21


static char r61318_hd_videooff_cmd0[] = {
	0x28, 0x00, 0x05, 0x80
};

static char r61318_hd_videooff_cmd1[] = {
	0x10, 0x00, 0x05, 0x80
};

static struct mipi_dsi_cmd r61318_hd_video_off_command[] = {
	{0x4, r61318_hd_videooff_cmd0, 0x32},
	{0x4, r61318_hd_videooff_cmd1, 0x96}
};

#define R61318_HD_VIDEO_OFF_COMMAND 2


static struct command_state r61318_hd_video_state = {
	0, 1
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/
static struct commandpanel_info r61318_hd_video_command_panel = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/
static struct videopanel_info r61318_hd_video_video_panel = {
	1, 0, 0, 0, 1, 1, 2, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane configuration                                                        */
/*---------------------------------------------------------------------------*/
static struct lane_configuration r61318_hd_video_lane_config = {
	4, 0, 1, 1, 1, 1
};

/*---------------------------------------------------------------------------*/
/* Panel timing                                                              */
/*---------------------------------------------------------------------------*/
static const uint32_t r61318_hd_video_timings[] = {
	//0x76, 0x18, 0x10, 0x00, 0x3C, 0x3E, 0x14, 0x1C, 0x12, 0x03, 0x04, 0x00
	//0x7A, 0x1A, 0x12, 0x00, 0x3E, 0x42, 0x16, 0x1E, 0x14, 0x03, 0x04, 0x00
	//0xa8, 0x1f, 0x17, 0x00, 0x2f, 0x2d, 0x1c, 0x4A, 0x29, 0x03, 0x04, 0x00
	//0x92, 0x1A, 0x12, 0x00, 0x3E, 0x42, 0x16, 0x1E, 0x14, 0x03, 0x04, 0x00
	//0x73, 0x19, 0x11, 0x00, 0x3c, 0x46, 0x14, 0x1c, 0x1c, 0x03, 0x04, 0x00
//	0xab, 0x1c, 0x14, 0x00, 0x2a, 0x27, 0x18, 0x1e, 0x21, 0x03, 0x04, 0x00
	0xa8, 0x1f, 0x17, 0x00, 0x2f, 0x2d, 0x1c, 0x4A, 0x29, 0x03, 0x04, 0x00
	//0x90, 0x21, 0x15, 0x00, 0x47, 0x4f, 0x1a, 0x25, 0x25, 0x03, 0x04, 0x00
	
};

static struct panel_timing r61318_hd_video_timing_info = {
	0, 4, 0x20, 0x2f
};

/*---------------------------------------------------------------------------*/
/* Panel reset sequence                                                      */
/*---------------------------------------------------------------------------*/
static struct panel_reset_sequence r61318_hd_video_reset_seq = {
	{1, 0, 1, }, {10, 20, 50, }, 2
};

/*---------------------------------------------------------------------------*/
/* Backlight setting                                                         */
/*---------------------------------------------------------------------------*/
static struct backlight r61318_hd_video_backlight = {
  //1, 1,255, 1, 1, "bl_ctrl_wled"
	0, 1, 255, 0, 2, 0
};

#endif /*_PANEL_R61318_HD_VIDEO_H_*/
