/* Copyright (c) 2014, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_SHARP_LQ050T1SX05_VIDEO_H_
#define _PANEL_SHARP_LQ050T1SX05_VIDEO_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/
static struct panel_config sharp_lq050t1sx05_video_panel_data = {
	"qcom,mdss_dsi_sharp_lq050t1sx05_video", "dsi:0:", "qcom,mdss-dsi-panel",
	10, 0, "DISPLAY_1", 0, 0, 60, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution sharp_lq050t1sx05_video_panel_res = {
	1080, 1920, 104, 56, 20, 0, 8, 6, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel color information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info sharp_lq050t1sx05_video_color = {
	24, 0, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel on/off command information                                          */
/*---------------------------------------------------------------------------*/

static char sharp_lq050t1sx05_cmd1[] = {0x02,0x00,0x23,0xC0,0xB0,0x04,0xff,0xff};
static char sharp_lq050t1sx05_cmd2[] = {0x02,0x00,0x23,0xC0,0xD6,0x01,0xff,0xff};
static char sharp_lq050t1sx05_cmd3[] = {0x29,0x00,0x05,0x80};
static char sharp_lq050t1sx05_cmd4[] = {0x11,0x00,0x05,0x80};
static char sharp_lq050t1sx05_cmd5[] = {0x02,0x00,0x15,0xC0,0x51,0xFF,0xff,0xff};
static char sharp_lq050t1sx05_cmd6[] = {0x02,0x00,0x15,0xC0,0x53,0x2C,0xff,0xff};
static char sharp_lq050t1sx05_cmd7[] = {0x02,0x00,0x15,0xC0,0x54,0x2C,0xff,0xff};
static char sharp_lq050t1sx05_cmd8[] = {0x02,0x00,0x15,0xC0,0x55,0x00,0xff,0xff};

static struct mipi_dsi_cmd sharp_lq050t1sx05_video_on_command[] = {
{ARRAY_SIZE(sharp_lq050t1sx05_cmd1), sharp_lq050t1sx05_cmd1, 0x00},
{ARRAY_SIZE(sharp_lq050t1sx05_cmd2), sharp_lq050t1sx05_cmd2, 0x00},
{ARRAY_SIZE(sharp_lq050t1sx05_cmd3), sharp_lq050t1sx05_cmd3, 0x00},
{ARRAY_SIZE(sharp_lq050t1sx05_cmd4), sharp_lq050t1sx05_cmd4, 0x78},
{ARRAY_SIZE(sharp_lq050t1sx05_cmd5), sharp_lq050t1sx05_cmd5, 0x00},
{ARRAY_SIZE(sharp_lq050t1sx05_cmd6), sharp_lq050t1sx05_cmd6, 0x00},
{ARRAY_SIZE(sharp_lq050t1sx05_cmd7), sharp_lq050t1sx05_cmd7, 0x00},
{ARRAY_SIZE(sharp_lq050t1sx05_cmd8), sharp_lq050t1sx05_cmd8, 0x00},
};

#define SHARP_LQ050T1SX05_VIDEO_ON_COMMAND 8


static char sharp_lq050t1sx05_videooff_cmd0[] = {
	0x28, 0x00, 0x05, 0x80
};

static char sharp_lq050t1sx05_videooff_cmd1[] = {
	0x10, 0x00, 0x05, 0x80
};

static struct mipi_dsi_cmd sharp_lq050t1sx05_video_off_command[] = {
	{0x4, sharp_lq050t1sx05_videooff_cmd0, 0x00},
	{0x4, sharp_lq050t1sx05_videooff_cmd1, 0x78}
};

#define SHARP_LQ050T1SX05_VIDEO_OFF_COMMAND 2


static struct command_state sharp_lq050t1sx05_video_state = {
	0, 1
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/
static struct commandpanel_info sharp_lq050t1sx05_video_command_panel = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/
static struct videopanel_info sharp_lq050t1sx05_video_video_panel = {
	1, 0, 0, 0, 1, 1, 2, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane configuration                                                        */
/*---------------------------------------------------------------------------*/
static struct lane_configuration sharp_lq050t1sx05_video_lane_config = {
	4, 0, 1, 1, 1, 1
};

/*---------------------------------------------------------------------------*/
/* Panel timing                                                              */
/*---------------------------------------------------------------------------*/
static const uint32_t sharp_lq050t1sx05_video_timings[] = {
	//0xf9, 0x3d, 0x34, 0x00, 0x58, 0x4d, 0x36, 0x3f, 0x53, 0x03, 0x04, 0x00
	0x9e, 0x43, 0x37, 0x00, 0x60, 0x58, 0x39, 0x45, 0x5b, 0x03, 0x04,0x00
};

static struct panel_timing sharp_lq050t1sx05_video_timing_info = {
	0, 4, 0x1e, 0x38
};

/*---------------------------------------------------------------------------*/
/* Panel reset sequence                                                      */
/*---------------------------------------------------------------------------*/
static struct panel_reset_sequence sharp_lq050t1sx05_video_reset_seq = {
	{1, 0, 1, }, {10, 20, 50, }, 2
};

/*---------------------------------------------------------------------------*/
/* Backlight setting                                                         */
/*---------------------------------------------------------------------------*/
static struct backlight sharp_lq050t1sx05_video_backlight = {
	0, 1, 255, 0, 0, 0
};

#endif /*_PANEL_SHARP_LQ050T1SX05_VIDEO_H_*/
